[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    # Create all necessary directories
    'mkdir -p storage/app/public/blog-images',
    'mkdir -p storage/logs',
    'mkdir -p storage/framework/{cache,sessions,views}',
    'mkdir -p public/storage',
    
    # Set permissions
    'chmod -R 755 storage public',
    
    # Laravel optimizations
    'php artisan config:cache',
    'php artisan route:cache', 
    'php artisan view:cache',
    
    # Storage link (try multiple methods)
    'php artisan storage:link || cp -rf storage/app/public/* public/storage/ || true',
    
    # Verify storage directory exists
    'ls -la public/ || true',
    'ls -la storage/app/public/ || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
