[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    # Storage link (try multiple methods)
    'chmod -R 755 storage public',
    'ls -la storage/app/public/*',
    'cp -rf storage/app/public/* public/storage/',
    
    # Verify storage directory exists
    'ls -la public/storage/blog-images || true',
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
